### PR TITLE
Reduce bundled library size by >50% with ES5 syntax

### PR DESCRIPTION
**Pull request by mmcgahan**
Just a little PR to cut the bundle size by half...

The major win is avoiding class inheritance, which wasn't giving us a huge amount of dev efficiency, and then a couple minor wins from avoiding Array & Object spread operators

before:

```
            Asset      Size  Chunks             Chunk Names
ux-capture.min.js  9.22 KiB       0  [emitted]  main
```

after:

```
            Asset      Size  Chunks             Chunk Names
ux-capture.min.js  4.15 KiB       0  [emitted]  main
```

There are probably other wins possible from using ES5 'classes' - I'll do a quick experiment to see if it's worth making the code that much uglier

### CODE REVIEW

**Comment by mmcgahan** [comment]
ES5 functions save an additional 1kB, so I'm including that change

**Review by sadafie — COMMENTED** [review]
This seems fine thought I'm wondering how much of a win it is w/in the consumer apps. As I developer I prefer writing ES6. Are we shaving off 50ms of time or 5? This is server rendered inline script, so I'm not sure how much of a net effect we're having by doing this.

**Comment by mmcgahan** [comment]
@sadafie since this is a payload size thing, it's something that will be more noticeable on slow connections, but since it's render-blocking, the payload cost is even more important than it would be for client application code. The fact that more than half of the bundled library code is currently feature shim code injected by Babel is a pretty bad code smell IMO.

I prefer writing ES6, but the corresponding ES5 for these features isn't particularly awkward to read or write (see the [raw code](https://github.com/meetup/ux-capture/blob/478fcc4afd2e3b5f6bfea2bc821f47f4620cc220/src/ExpectedMark.js), so I'd prefer to pay the cost of writing 'legacy' class JS rather than push it downstream to consumer apps.

**Comment by mmcgahan** [comment]
Also, if the `class` syntax feels like the greatest loss in terms of ergonomics, we can put that back in by reverting https://github.com/meetup/ux-capture/pull/21/commits/9b5f7ca0072ae9d7df616486dd1834dd2f318280 - we still save ~40% of the bundle size just by eliminating the class inheritance (`extends UXBase`)

**Comment by sergeychernyshev** [comment]
I don't have a very strong preference. I agree with @mmcgahan that it's blocking and the smaller it is the better. Good news is that it doesn't block CSS, but still blocks the rest. That being said, it's 10K uncompressed and 2.6K on the wire (gzipped).

Also, we have plenty of other code that is even more voluminous, like NewRelic, font loader library and probably other things.

Code doesn't seem to be overly complex so having it ES5 is probably not a huge deal - the goal is to keep core library simple even if we add functionality so I feel it might be OK, but didn't expect @mmcgahan to jump on this as an order of priority ;)

**Review by sadafie — APPROVED** [review]

**Review by sergeychernyshev — APPROVED** [review]
A lot of change for size reasons. Hope it's worth it ;)

**Comment by mmcgahan** [comment]
happy to revisit this in the future if we feel held back by syntax options, but i figure it's a good baseline implementation

**Pull request merged**
